/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package deepsea.app;


import deepsea.utilities.Server;
import deepsea.utilities.Scheduler;
import deepsea.utilities.ReadFileConf;

import java.util.Vector;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;


public class App {
    public static void main(String[] args) {

        ReadFileConf conf = new ReadFileConf();
        /*\/ atribuir servidores pacs; */
        Vector<Server> servers = conf.readJsonConf();

        Scheduler sche = new Scheduler();
        sche.setServers(servers);
        /*\/ iniciar schedule para multiplos servidores; */
        if(args.length == 0 && conf.seArqConfExists()) {
            sche.iniParallel();
        }

        /*\/ opções de argumentos de linha de comando; */
        if(args.length > 0 && args[0] != null){
            /*\/ criar arquivo de configuração; */
            if(args[0].equalsIgnoreCase("-c") && !conf.seArqConfExists()){
                File fileConf = new File("deepsea.json");
                if(!fileConf.exists()){
                    try {
                        FileWriter myWriter = new FileWriter("deepsea.json", false);
                        myWriter.write("{\n");
                        myWriter.write("\t\"servers\":\n");
                        myWriter.write("\t[\n");
                        myWriter.write("\t\t{ \"host\": \"<ip-servidor>\", \"user\": \"<usuario>\", \"password\": \"<senha>\", \"folder\": \"</home/pasta-imagens>\" },\n");
                        myWriter.write("\t\t{ \"host\": \"\", \"user\": \"\", \"password\": \"\", \"folder\": \"\" }\n");
                        myWriter.write("\t]\n");
                        myWriter.write("}\n");
                        myWriter.close();
                    } catch (IOException e) { e.printStackTrace(); }
                }
            }
        }

    }
}
